# Copyright (c) 2026, Bunood and contributors
# For license information, please see license.txt
"""Compiled asset paths. **GENERATED BY build.mjs — DO NOT EDIT BY HAND.**

Rewritten on every ``npm run build``. ``hooks.py`` imports these so the content
hash reaches ``app_include_css`` without anyone maintaining a version string.

Never hand-edit a path to contain ``.bundle.``: Frappe would treat it as a logical
bundle name, resolve it against a stale ``assets.json``, and prefix it with
``rtl_`` on Arabic sites. See ARCHITECTURE.md section 6.
"""

THEME_CSS = "/assets/bunood_theme/dist/css/bunood.5279c7fe.css"
THEME_JS = "/assets/bunood_theme/dist/js/bunood.21dbb2c0.js"
