# Copyright (c) 2026, Bunood and contributors
# For license information, please see license.txt
"""Compiled asset paths. **GENERATED BY build.mjs — DO NOT EDIT BY HAND.**

Rewritten on every ``npm run build``. ``hooks.py`` imports these so the content
hash reaches ``app_include_css`` without anyone maintaining a version string.

Never hand-edit a path to contain ``.bundle.``: Frappe would treat it as a logical
bundle name, resolve it against a stale ``assets.json``, and prefix it with
``rtl_`` on Arabic sites. See ARCHITECTURE.md section 6.
"""

THEME_CSS = "/assets/bunood_theme/dist/css/bunood.e7a48ee5.css"
WEB_CSS = "/assets/bunood_theme/dist/css/bunood-web.097877f3.css"
EMAIL_CSS = "/assets/bunood_theme/dist/css/bunood-email.1c5e93a1.css"
PRINT_CSS = "/assets/bunood_theme/dist/css/bunood-print.bdcc90e4.css"
REPORT_LANDING_CSS = "/assets/bunood_theme/dist/css/bnd-report-landing.996a5158.css"
STUDIO_CSS = "/assets/bunood_theme/dist/css/bnd-studio.1ba5dc82.css"
POS_CSS = "/assets/bunood_theme/dist/css/bnd-pos.9908dfe2.css"
THEME_JS = "/assets/bunood_theme/dist/js/bunood.7de267be.js"
STUDIO_JS = "/assets/bunood_theme/dist/js/bnd-studio.c376e1d6.js"
REPORT_LANDING_JS = "/assets/bunood_theme/dist/js/bnd-report-landing.d6e61f25.js"
BANKING_JS = "/assets/bunood_theme/dist/js/bnd-banking.3e22dff8.js"
FINANCE_CLOSE_JS = "/assets/bunood_theme/dist/js/bnd-finance-close.24dabb5e.js"
JOURNAL_WORKBENCH_JS = "/assets/bunood_theme/dist/js/bnd-journal-workbench.55fa6e87.js"
POS_JS = "/assets/bunood_theme/dist/js/bnd-pos.a4f0f9af.js"
