# Copyright (c) 2026, Bunood and contributors
# For license information, please see license.txt
"""Compiled asset paths. **GENERATED BY build.mjs — DO NOT EDIT BY HAND.**

Rewritten on every ``npm run build``. ``hooks.py`` imports these so the content
hash reaches ``app_include_css`` without anyone maintaining a version string.

Never hand-edit a path to contain ``.bundle.``: Frappe would treat it as a logical
bundle name, resolve it against a stale ``assets.json``, and prefix it with
``rtl_`` on Arabic sites. See ARCHITECTURE.md section 6.
"""

HOME_CSS = "/assets/bunood_theme/dist/css/bnd-home.45e082d4.css"
THEME_CSS = "/assets/bunood_theme/dist/css/bunood.3fb330f4.css"
WEB_CSS = "/assets/bunood_theme/dist/css/bunood-web.c06aa4f9.css"
EMAIL_CSS = "/assets/bunood_theme/dist/css/bunood-email.1c5e93a1.css"
PRINT_CSS = "/assets/bunood_theme/dist/css/bunood-print.0f2b88c4.css"
REPORT_LANDING_CSS = "/assets/bunood_theme/dist/css/bnd-report-landing.8786ef01.css"
STUDIO_CSS = "/assets/bunood_theme/dist/css/bnd-studio.1fd016bb.css"
POS_CSS = "/assets/bunood_theme/dist/css/bnd-pos.513ba23d.css"
ZATCA_CSS = "/assets/bunood_theme/dist/css/bnd-zatca.c6855253.css"
HOME_JS = "/assets/bunood_theme/dist/js/bnd-home.a216bc54.js"
THEME_JS = "/assets/bunood_theme/dist/js/bunood.47549bc8.js"
STUDIO_JS = "/assets/bunood_theme/dist/js/bnd-studio.fe49b4ef.js"
REPORT_LANDING_JS = "/assets/bunood_theme/dist/js/bnd-report-landing.253f7a51.js"
BANKING_JS = "/assets/bunood_theme/dist/js/bnd-banking.67465a0d.js"
FINANCE_CLOSE_JS = "/assets/bunood_theme/dist/js/bnd-finance-close.e914a5e3.js"
JOURNAL_WORKBENCH_JS = "/assets/bunood_theme/dist/js/bnd-journal-workbench.756d4dc9.js"
ASSET_WORKBENCH_JS = "/assets/bunood_theme/dist/js/bnd-asset-workbench.9d7a461d.js"
POS_JS = "/assets/bunood_theme/dist/js/bnd-pos.97ea7607.js"
ZATCA_JS = "/assets/bunood_theme/dist/js/bnd-zatca.f8323fcb.js"
