# Copyright (c) 2026, Bunood and contributors
# For license information, please see license.txt
"""Per-site brand stylesheet generation.

WHAT
    Renders the customer's brand colours into a small CSS file, writes it atomically
    to the site's own ``public/files`` with a content-hashed filename, reaps older
    copies, and records the URL on Theme Settings for :mod:`bunood_theme.context` to
    inject.

WHY A FILE AND NOT A DYNAMIC ROUTE
    The stylesheet is render-blocking in ``<head>``. A dynamic route would make every
    desk page load wait on a synchronous Python request through gunicorn, and would
    return a 500 *on a stylesheet* whenever anything upstream failed. A static file is
    served by nginx with no Python involved and keeps working even if the database is
    down. This mirrors Frappe's own ``Website Theme``
    (``website/doctype/website_theme/website_theme.py:92-121``), which generates
    per-site CSS to the same location with a hashed suffix. Note the strategy is NOT
    the same and must not be copied: theirs is a RANDOM suffix over deleted-on-write
    files, ours is a digest of the content over files kept for live desks. Item 32's
    release review found this file doing theirs while documenting ours.

WHY THE FILENAME IS HASHED
    nginx in this deployment sets no ``Cache-Control`` on ``/files`` — only
    ``Last-Modified`` and ``ETag`` (verified by curl through the frontend). Browsers
    then apply RFC 9111 heuristic freshness, roughly ``(now - Last-Modified) / 10``.
    With a stable URL, a colour change would stay invisible to returning users for
    hours or days, with no revalidation request at all. A content hash makes the URL
    immutable, which turns the missing header from a hazard into a non-issue — and
    removes any need for the ``?v=N`` suffixes the previous version maintained by hand.

WHY NEVER FRAPPE'S VARIABLE NAMES
    Frappe implements dark mode by remapping its OWN variable names under
    ``[data-theme="dark"]``. Both that and ``:root`` have specificity (0,1,0), so a
    later sheet setting e.g. ``--bg-color`` at ``:root`` wins in BOTH modes and
    silently kills dark mode. This file therefore emits only our namespaced tokens;
    ``_bridge.scss`` in the compiled bundle maps them onto Frappe's names inside
    correctly scoped blocks. See ARCHITECTURE.md sections 1 and 5.

    (This used to read "why only tokens". Item 7(b) added ``@font-face`` rules and
    one ``body { font-family }`` — neither touches a Frappe variable name, which
    was always the actual constraint. The body rule COMPOSES Frappe's stack rather
    than replacing it: the Arabic family is prepended and ``var(--font-stack)``
    follows, so Latin text falls through to exactly what Frappe chose.)
"""

import hashlib
import os

import frappe

from bunood_theme import palette
from bunood_theme.typography import DEFAULT_FACE, FACES, ARABIC_RANGE

#: Subdirectory under the site's ``public/files``. Kept in its own folder so reaping
#: can glob safely without touching user uploads.
BRAND_DIR = "bunood"

#: Filename stem; the content hash and ``.css`` are appended.
BRAND_STEM = "brand_"

#: Every Theme Settings field whose value is BAKED INTO the generated stylesheet.
#:
#: WHY THIS LIST EXISTS (item 32, found by an adversarial release review). The sheet
#: is regenerated by ``on_update``, which only fires on a real document save.
#: ``frappe.db.set_single_value`` does not fire it — and that is exactly how the smoke
#: suite writes settings. Before item 32 that was harmless for everything the suite
#: touches, because the only fields it wrote were desk attributes the sheet never
#: reads. Item 32 made ``tagline`` a sheet input, and the suite writes ``tagline`` on
#: every run as its save-round-trip scratch field — so a run left the DB restored and
#: the SHEET carrying ``smoke-seed-<timestamp>``, which then rendered on the sign-in
#: page indefinitely. Measured in exactly that state before this was added.
#:
#: The suite consults this list and regenerates when it writes one of these. Anything
#: added to ``render_brand_css`` or ``render_typography_css`` that reads a settings
#: field belongs here in the same commit; the standing check
#: ``login: the served tagline matches the stored one`` is the backstop that notices
#: when it does not.
BRAND_INPUTS = (
    "brand_color",
    "accent_color",
    "brand_color_dark",
    "accent_color_dark",
    "default_density",
    "tagline",
    "arabic_font",
)


def render_brand_css(settings=None) -> str:
    """Build the CSS text for the current Theme Settings.

    Emits four blocks, and the split matters:

    * ``:root`` — mode-independent tokens (the raw seeds, spacing, radii).
    * ``html[data-theme="light"]`` / ``html[data-theme="dark"]`` — the light and dark
      *derived* steps. Dark is SELECTED, not computed by lightening light: the
      customer may supply explicit dark seeds, and where they do not we derive from a
      dark surface rather than flipping the light values.
    * ``@media (prefers-color-scheme: dark) html[data-theme="automatic"]`` — the
      same dark values, for the mode Frappe accepts but ships no rules for.

    One seed produces a coherent scale for whatever colour a customer picks — the
    alternative, hand-authoring 12 steps per tenant, does not scale for a
    white-label product.

    CONTRAST IS GUARANTEED HERE, NOT HOPED FOR (checklist item 32). Before this,
    every surface was re-derived from the seed and nothing validated the result:
    a yellow seed measured 1.62:1 for white-on-brand, and the SHIPPED default was
    already failing at 4.27:1. :mod:`bunood_theme.palette` now fits each ink and
    fill to the surfaces the seed actually produces, so the ratios hold for any
    colour a tenant enters. Values are emitted as concrete hex rather than live
    ``color-mix()`` for exactly that reason: what CI measured and what the browser
    paints are then the same string.

    Args:
        settings: an optional pre-fetched Theme Settings document, to avoid a second
            read when the caller already has it (e.g. from ``on_update``).

    Returns:
        The stylesheet as a string. Never raises; falls back to shipped defaults.
    """
    s = settings or frappe.get_single("Theme Settings")

    brand = (getattr(s, "brand_color", None) or "#4d8756").strip()
    accent = (getattr(s, "accent_color", None) or "#4463f0").strip()
    # Empty dark seeds fall back to the light ones. That is deliberate: a customer who
    # has not thought about dark mode still gets a coherent (if less tuned) result,
    # rather than an unthemed one.
    brand_dark = (getattr(s, "brand_color_dark", None) or brand).strip()
    accent_dark = (getattr(s, "accent_color_dark", None) or accent).strip()

    # Site-default density (decision "G with C"). Emitted at :root, which the
    # per-user attribute blocks in _tokens.scss deliberately outrank at (0,1,1)
    # vs (0,1,0) — so this sets the default without ever fighting a user's own
    # choice. Only the Compact values are emitted: Comfortable is already the
    # compiled bundle's :root default, and re-stating it here would only add
    # bytes to every site's brand sheet. NO font tokens belong here, ever —
    # compact changes geometry, not readability.
    density = ""
    if (getattr(s, "default_density", None) or "").strip().lower() == "compact":
        density = """
  --bnd-row-h: 24px;
  --bnd-control-h: 26px;
  --bnd-pad-y: 3px;"""

    # Every seed-dependent value comes from palette.derive — the SAME function
    # tools/contrast_gate.py measures in CI. This file formats; it does not
    # decide. A colour computed here and merely checked there would be a check on
    # a copy, and the copy is what would drift.
    #
    # A bad seed degrades to the compiled bundle's defaults rather than to an
    # illegible desk: derive() raises only when no fill can satisfy both
    # constraints, write_brand_css catches, and context.py appends nothing.
    try:
        light = palette.derive(brand, accent, "light")
        dark = palette.derive(brand_dark, accent_dark, "dark")
    except ValueError:
        frappe.log_error("bunood_theme.brand: seed rejected by palette.derive")
        raise

    def block(tokens: dict, indent: str = "  ") -> str:
        # Sorted, so a colour change produces a diff of the values that changed
        # rather than a reshuffle. The file is regenerated wholesale on every
        # save; stable ordering is what makes it readable when debugging one.
        return "\n".join(f"{indent}{k}: {v};" for k, v in sorted(tokens.items()))

    # The whole sheet is @media screen — deliberately. This file loads AFTER the
    # compiled bundle and its mode blocks tie the bundle's selectors at (0,1,1),
    # so later-sheet-wins would let a dark brand value beat the bundle's
    # @media print force-light override (measured live 2026-07-30: --bg-color
    # stayed dark in print emulation until this wrapper existed). Brand colour
    # is a screen concern; on paper the bundle's print block owns every token
    # unopposed, with no !important anywhere.
    #
    # The `automatic` block is emitted too, and that is not decoration. Frappe
    # accepts "Automatic" for User.desk_theme and ships no prefers-color-scheme
    # rules at all; _tokens.scss supplies the fallback, but without this block a
    # tenant's own colours would stop at the mode boundary and an Automatic user
    # on a dark OS would see the SHIPPED green rather than theirs.
    # ── The sign-in page's own dark scopes (item 32) ─────────────────────────
    #
    # A WEBSITE PAGE CARRIES NO `data-theme`, so neither dark selector above can
    # match one — and the light selector's `html:not([data-theme])` arm can. That
    # asymmetry is a real defect and it hides at the shipped seed: /login in dark
    # fell back to `_tokens.scss`'s LITERAL dark values, which are fitted for the
    # shipped green. A customer with a blue brand would have got a green art
    # panel and a green primary button on their dark sign-in page, and every
    # check would have passed, because this site's seed IS the shipped one.
    # Found by reading the generated file rather than by a test.
    #
    # THE SELECTORS ARE DERIVED FROM `context.AUTH_CLASSES`, not restated. That
    # map is the one place a login value becomes a class name; writing
    # "bnd-auth-theme-dark" here as a string would be the second copy, and this
    # repo's every critical defect traces to one.
    from bunood_theme.context import AUTH_BODY_CLASS, AUTH_CLASSES, WEB_BODY_CLASS, WEB_CLASSES

    _modes = AUTH_CLASSES["login_theme"]
    _dark_cls = f"body.{AUTH_BODY_CLASS}-{_modes['Always Dark']}"
    _follow = (
        f"body.{AUTH_BODY_CLASS}"
        f":not(.{AUTH_BODY_CLASS}-{_modes['Always Light']})"
        f":not(.{AUTH_BODY_CLASS}-{_modes['Always Dark']})"
    )

    # ── The rest of the website's dark scope (item 33, slice 2b) ─────────────
    #
    # THE SAME DEFECT AS ABOVE, ONE SURFACE OVER, and it would have hidden in the
    # same place. Every website page now carries `body.bnd-web`, and none of them
    # carries `data-theme` — so without this the portal's dark mode falls through
    # to `_tokens.scss`'s literal dark values, which are fitted for the SHIPPED
    # seed. Measured before this line existed: `--bnd-page` on `/orders` under a
    # dark OS resolved to the LIGHT `color-mix()`, i.e. dark was not applying at
    # all, and no value comparison on this site could have told a wrong dark
    # palette from a right one because our seed IS the shipped one.
    #
    # BOTH ARMS NOW (slice 6). Slice 2b shipped only the follow-OS one, because
    # `web_theme`'s classes did not exist yet and a guard nothing can satisfy is
    # the untested-branch trap volunteered rather than inherited. They arrive here
    # with the axis, so both are exercised by the same commit.
    #
    # DERIVED FROM `WEB_CLASSES`, never restated — the same rule the auth arm
    # above follows, and for the same reason: that map is the ONE place a value
    # becomes a class name, and writing "bnd-web-theme-dark" here as a string
    # would be the second copy this repo's every critical defect traces to.
    _web_modes = WEB_CLASSES["web_theme"]
    _dark_cls += f", body.{WEB_BODY_CLASS}-{_web_modes['Always Dark']}"
    _follow += (
        f", body.{WEB_BODY_CLASS}"
        f":not(.{WEB_BODY_CLASS}-{_web_modes['Always Light']})"
        f":not(.{WEB_BODY_CLASS}-{_web_modes['Always Dark']})"
    )

    # The tagline, which Theme Settings has promised on this page since day one
    # and never delivered. Its slot is a LITERAL in Frappe's own template
    # (`www/login.html:91-104`'s `logo_section` macro takes title and subtitle and
    # every call site passes strings), and `www/login.py` publishes no context key
    # for it — so there is no server-side seam and injecting a node would mean
    # end-of-body JS, i.e. a flash. It travels as a custom property and
    # `web/_login.scss` renders it.
    #
    # `content: none` is the absent case, so an unset tagline generates NO
    # pseudo-element rather than an empty box with margins.
    tagline = _css_string(s.get("tagline"))
    tagline_decl = f"\n  --bnd-login-tagline: {tagline};" if tagline else ""

    return f"""@media screen {{
:root {{
  --bnd-brand:  {brand};
  --bnd-accent: {accent};{density}{tagline_decl}
}}
html[data-theme="light"], html:not([data-theme]) {{
{block(light)}
}}
html[data-theme="dark"], {_dark_cls} {{
{block(dark)}
}}
@media (prefers-color-scheme: dark) {{
  html[data-theme="automatic"], {_follow} {{
{block(dark, "    ")}
  }}
}}
}}
"""


def _css_string(value) -> str:
    """Quote a customer-entered string for a CSS ``content:`` value, or return "".

    ESCAPED, NOT TRUSTED. This lands in a stylesheet an admin can edit the input
    for, so a stray quote or backslash would end the string early and everything
    after it would parse as CSS. Backslash first (or it would re-escape the
    escapes), then the quote, then the line terminators CSS strings may not
    contain. Anything left is inert: a CSS string cannot open a rule.

    THE NEWLINE SET IS CSS SYNTAX'S, NOT PYTHON'S. CSS Syntax 4.2 defines a newline as
    U+000A, U+000D **and U+000C FORM FEED**, and an unescaped one inside a string
    is a parse error. The first cut handled the first two and not the third, so a
    tagline pasted with a form feed in it would kill the declaration it sits in.
    Not an injection — the quote and the backslash are already escaped, and a bad
    string terminates its own declaration rather than the sheet — but a
    customer-entered value that silently drops a feature is the thing this helper
    exists to prevent. Found in item 32's release review; the tagline is the only
    caller today and it is the one an admin pastes into.
    """
    if not value:
        return ""
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    for newline in ("\r\n", "\n", "\r", "\f"):
        text = text.replace(newline, " ")
    return f'"{text}"'


def render_typography_css(settings) -> str:
    """The Arabic face block: ``@font-face`` + tokens + one body rule.

    Emitted OUTSIDE ``@media screen`` — a printed Arabic invoice wants the
    face as much as the desk does, and ``@font-face`` at top level serves both.

    THE MECHANISM IS ``unicode-range``: the face APPLIES only to Arabic
    glyphs, so Arabic DATA on an English desk (a workspace named in Arabic)
    gets it, which no language- or direction-scoped rule can do. That is why
    the body rule is UNSCOPED — prepending an Arabic-only family changes no
    Latin rendering, ever. The DOWNLOAD is another matter: Chromium fetches on
    in-range characters anywhere in the DOM, and Frappe's boot script carries
    native language names on every desk, so in practice every browser fetches
    the selected face once and caches it forever (measured; see
    typography.py's docstring for the retraction this sentence replaced).

    Only the SELECTED face is emitted. The unused catalogue is never
    referenced, so no browser anywhere downloads a face the admin did not
    choose. "System" emits nothing at all — the honest zero-payload option.

    ``--bnd-lh-arabic`` is declared here but CONSUMED in ``_cursive.scss``,
    inside the cursive-language scope: leading is a per-face fact (Cairo needs
    reining in at 1.62 where Plex wants 1.7), but WHERE looser leading applies
    is a language question, and the stylesheet already owns that list.
    """
    face = FACES.get((getattr(settings, "arabic_font", None) or DEFAULT_FACE).strip())
    if not face or not face.get("family"):
        return ""

    faces_css = "\n".join(
        f"""@font-face {{
  font-family: "{face["family"]}";
  src: url(/assets/bunood_theme/fonts/{f["file"]}) format("woff2");
  font-weight: {f["weight"]};
  font-style: normal;
  /* swap: a slow font must never block first paint (item 36). The fallback
     chain renders immediately and the face swaps in when it arrives. */
  font-display: swap;
  unicode-range: {ARABIC_RANGE};
}}"""
        for f in face["files"]
    )

    lh = f"\n  --bnd-lh-arabic: {face['line_height']};" if face.get("line_height") else ""
    return f"""{faces_css}
:root {{
  --bnd-font-arabic: "{face["family"]}", {face["fallback"]};{lh}
}}
body {{
  font-family: var(--bnd-font-arabic), var(--font-stack);
}}
"""


#: Cache key holding a URL produced by a READ-PATH repair (``persist=False``).
#:
#: A repair made while serving a page cannot record itself in the database — see
#: :func:`write_brand_css`'s ``persist`` argument — so it records itself here instead.
#: The cache is not transactional, so it survives the request that wrote it, and it is
#: site-namespaced by Frappe. :func:`bunood_theme.context._brand_css_url` treats it as
#: strictly subordinate to the stored value: the database wins whenever ITS file is on
#: disk, so a stale key can never mask a real save.
HEAL_CACHE_KEY = "bunood_theme:healed_brand_css_url"


def write_brand_css(settings=None, persist: bool = True) -> str | None:
    """Generate, write and register the brand stylesheet. Returns its URL or ``None``.

    Called from ``Theme Settings.on_update`` (so a save takes effect immediately) and
    from ``after_migrate`` (so a database-only restore, which leaves a stale or absent
    file, self-heals).

    The write is atomic — temp file plus :func:`os.replace` — because the file is being
    served by nginx while we rewrite it, and a partially written stylesheet would be
    handed to a live browser.

    Args:
        persist: whether this call may RECORD the result — write ``brand_css_url`` and
            reap superseded files. ``False`` renders and writes the file and returns
            its URL, touching neither the database nor its neighbours.

    WHY ``persist`` EXISTS, AND WHY THE READ PATH MUST PASS ``False``. The self-heal in
    :func:`bunood_theme.context._brand_css_url` runs inside ``update_website_context``,
    i.e. while serving a GET. **Frappe rolls back the transaction at the end of a
    non-writing request**, so the ``set_single_value`` below was discarded every time:
    the stored URL stayed stale, the next request found the same missing file, and the
    heal ran again — for every request, forever, until somebody saved Theme Settings.
    Each of those took a write lock on ``tabSingles`` to record something that was then
    thrown away, so concurrent desk loads serialised on a row lock in a state whose
    whole point was that it should be invisible. Found in item 32's release review.

    The repair is still correct without the write, and THAT is what makes this fix
    small: the filename is a digest of the content (see below), so the URL is a pure
    function of the settings. The read path does not need to remember anything to be
    right — it only wanted to, to avoid repeating the render. That job moved to
    :data:`HEAL_CACHE_KEY`, which is not transactional.

    Reaping is gated on ``persist`` for the same reason and one of its own: deleting a
    neighbour's file is not this request's business, and a read that reaps is a read
    that can 404 a stylesheet another live desk is still holding.

    Returns:
        The public URL (``/files/bunood/brand_<hash>.css``), or ``None`` if generation
        failed. A ``None`` result is safe: :mod:`bunood_theme.context` simply appends
        nothing and the compiled bundle's own defaults apply, which is why that bundle
        must always declare the complete token set.
    """
    try:
        s = settings or frappe.get_single("Theme Settings")
        css = render_brand_css(s) + render_typography_css(s)

        # HASH THE CONTENT. Everything above depends on it: the URL is immutable
        # only if the name is a function of the bytes, and an unchanged save has to
        # keep the same URL or every warm cache is thrown away for nothing.
        #
        # THIS LINE READ ``frappe.generate_hash(css, 8)`` AND THAT IS NOT A CONTENT
        # HASH. Its own docstring is "Generates a random hash using best available
        # randomness source"; the body is ``secrets.token_hex`` and the ``txt``
        # argument is DISCARDED. So every save and every ``after_migrate`` minted a
        # fresh name for byte-identical CSS — ``os.path.exists`` below could never
        # short-circuit, :func:`_reap_old` spent its eight-file budget of
        # still-referenced URLs on nothing, and returning browsers re-downloaded a
        # stylesheet they already had. Found in item 32's release review.
        #
        # The comment cited Frappe's Website Theme as precedent for "8 hex chars",
        # and that is where the mistake came from: ``website_theme.py`` does use
        # eight, but its own comment reads ``# add a random suffix`` and it DELETES
        # the previous files on every generate. The length was copied; the semantics
        # were not, and ours keeps old files precisely so live desks do not 404.
        #
        # It was also a deadline. ``txt`` is deprecated, emits a deprecation warning
        # on every call, and is REMOVED in Frappe v17 — where the resulting TypeError
        # would be caught by this function's own ``except Exception``, ``None``
        # returned, and the brand stylesheet would simply stop being generated, on
        # every site, reported by nothing louder than an error log.
        #
        # TWELVE hex chars, not eight. Content addressing introduces a failure mode
        # random naming did not have: on a collision the existing file is served and
        # the new content is never written, so the customer's colour change silently
        # does not happen. 48 bits puts that below the noise floor for any real
        # number of saves; the four extra characters cost nothing in a URL no human
        # reads.
        digest = hashlib.sha256(css.encode("utf-8")).hexdigest()[:12]
        filename = f"{BRAND_STEM}{digest}.css"

        folder = os.path.join(frappe.get_site_path("public", "files"), BRAND_DIR)
        os.makedirs(folder, exist_ok=True)
        target = os.path.join(folder, filename)

        if not os.path.exists(target):
            tmp = target + ".tmp"
            with open(tmp, "w", encoding="utf-8") as fh:
                fh.write(css)
            os.replace(tmp, target)  # atomic on the same filesystem

        url = f"/files/{BRAND_DIR}/{filename}"

        # A read-path repair stops here: the file now exists and the URL is correct,
        # which is everything the request being served needs.
        if not persist:
            return url

        _reap_old(folder, keep=filename)
        # set_value, not doc.save(): saving inside on_update would recurse, and this
        # field is derived state the user never edits.
        #
        # update_modified=False is LOAD-BEARING: this runs inside on_update,
        # AFTER the save stamped `modified` — letting this write bump it again
        # leaves every open form instantly stale, and the user's next save
        # dies with TimestampMismatchError ("modified after you have opened
        # it" — reported live 2026-07-30). Skipping the unchanged case also
        # spares a pointless write on every save.
        if frappe.db.get_single_value("Theme Settings", "brand_css_url") != url:
            frappe.db.set_single_value(
                "Theme Settings", "brand_css_url", url, update_modified=False
            )
        # The stored value is authoritative again, so any read-path repair is now
        # noise. Dropping it here is what stops a heal from outliving a real save.
        frappe.cache().delete_value(HEAL_CACHE_KEY)
        return url

    except Exception:
        frappe.log_error("bunood_theme.brand.write_brand_css failed")
        return None


#: How many superseded brand files to keep. Generous on purpose: a file is a
#: couple of KB, and every file deleted too early is a desk that loses its
#: colours mid-session.
REAP_KEEP = 8


def _reap_old(folder: str, keep: str) -> None:
    """Delete old brand files, keeping ``keep`` plus the ``REAP_KEEP`` newest.

    Old hashed files are left behind by every colour change. They are unbounded,
    so they are pruned here rather than by a scheduled job — but NOT to one.
    Keeping only the current file guaranteed a 404 for every holder of an older
    URL, and both holders are real, measured 2026-08-08:

    * An OPEN TAB. Its ``<link>`` was rendered before the colour change; the
      desk is an SPA, so that head element lives for the whole session, and its
      next revalidation answered 404-as-HTML — "Refused to apply style ...
      MIME type ('text/html')", and a desk with no brand colours. This was
      HANDOVER's "open tab loses brand colours" item.
    * A DATABASE-ONLY RESTORE. The smoke suite and the settings sweep snapshot
      ``tabSingles`` and write it back raw, which restores ``brand_css_url``
      pointing at a hash whose file the sweep's own saves had reaped. The
      stored URL and the disk then disagree until something calls
      :func:`write_brand_css` again — found as a stale-brand-CSS console error
      the suite had been allowlisting rather than explaining.

    A window of eight outlives both: tabs get a working stylesheet for the
    last several changes, and a restore lands on a URL whose file still
    exists. Deliberately tolerant: a failure to delete must never fail the
    save.
    """
    try:
        candidates = []
        for name in os.listdir(folder):
            if name.startswith(BRAND_STEM) and name.endswith(".css") and name != keep:
                path = os.path.join(folder, name)
                try:
                    candidates.append((os.path.getmtime(path), path))
                except OSError:
                    pass
        candidates.sort(reverse=True)
        for _, path in candidates[REAP_KEEP:]:
            try:
                os.remove(path)
            except OSError:
                pass
    except OSError:
        pass
